# Generated by Django 4.2.5 on 2023-09-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0003_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
