# Generated by Django 4.2.5 on 2023-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_alter_contacts_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
